services:
  bot:
    image: accurateherbchecker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./data/db:/app/data/db
    env_file:
      - .env