# Configuration settings
bot_prefix: "/"
intents:
  messages: true
  guilds: true
  reactions: false
  members: false
  presences: false
  message_content: true

headers:
  user_agent: "Herb Run - Realtime Check"
  from: "@mistrustful on discord and osrs"

logging:
  level: INFO #logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  handlers:
    - type: console
    - type: file
      filename: logs/app.log
